# List the start-up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Install Dependencies
    command: npm install --save-dev prisma typescript ts-node @types/node nodemon

  - name: Initialize Prisma
    command: npx prisma init --datasource-provider postgresql
